# Generated by Django 4.0.5 on 2022-06-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0002_project_average_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='average_score',
        ),
        migrations.AddField(
            model_name='project',
            name='rank',
            field=models.BigIntegerField(null=True),
        ),
    ]
