# Generated by Django 4.0.5 on 2022-06-12 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0003_remove_project_average_score_project_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_submited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='rank',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
