# Generated by Django 4.0.5 on 2022-06-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0005_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='average_score',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
