# Generated by Django 4.0.5 on 2022-06-12 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0007_vote_date_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='awwards.project'),
        ),
    ]
