# Generated by Django 4.0.5 on 2022-06-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0008_alter_vote_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='content',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='design',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='usability',
            field=models.IntegerField(default=0),
        ),
    ]
