# Generated by Django 4.0.5 on 2022-06-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0009_vote_content_vote_design_vote_usability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='design',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
    ]
