# Generated by Django 4.0.5 on 2022-06-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0010_alter_vote_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='content',
            field=models.IntegerField(choices=[], default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='usability',
            field=models.IntegerField(choices=[], default=0),
        ),
    ]
