# Generated by Django 4.0.5 on 2022-06-16 22:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0013_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default=2, max_length=255, verbose_name='profile_image'),
        ),
    ]
