# Generated by Django 4.0.5 on 2022-06-16 23:13

import cloudinary.models
from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0016_alter_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dvhid4k2j/image/upload/v1655420670/ian-schneider-TamMbr4okv4-unsplash_fgs9ua.jpg', max_length=255, verbose_name='profile_image'),
        ),
    ]
