# Generated by Django 4.0.5 on 2022-06-16 23:14

import cloudinary.models
from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0017_alter_profile_country_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dvhid4k2j/image/upload/v1655420581/davisuko-5E5N49RWtbA-unsplash_d8yuyx.jpg', max_length=255, verbose_name='profile_image'),
        ),
    ]
