# Generated by Django 4.0.5 on 2022-06-16 23:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0018_alter_profile_country_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dvhid4k2j/image/upload/v1655419775/Snapchat-667489474_tywlo1.jpg', max_length=255, verbose_name='profile_image'),
        ),
    ]
